apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookverse-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: bookverse.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bookverse-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: bookverse-backend
                port:
                  number: 80
