-- 审计字段迁移脚本
ALTER TABLE account ADD COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE account ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE product ADD COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE product ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE orders ADD COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE orders ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE order_item ADD COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE coupon ADD COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE coupon ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE book_review ADD COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE message ADD COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE announcement ADD COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE announcement ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE admin_log ADD COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP;
